
const D=window.APP_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let state={day:'all',doccat:'Todos'},map;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===v));if(v==='mapa')setTimeout(initMap,60)}window.showView=showView;$$('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.v));
function card(x,i,prefix='plan'){let checked=localStorage.getItem(prefix+i)==='1';return `<article class="card plan ${esc(x.slot)} ${checked?'done':''}"><div class="checkrow"><input type="checkbox" data-key="${prefix+i}" ${checked?'checked':''}><div style="flex:1"><div class="top"><span class="slot">${esc(x.slot)}</span><span class="time">${esc(x.time||'Flexible')}</span></div><h3>${esc(x.activity)}</h3><div class="muted">📍 ${esc(x.zone)} · ${esc(x.date)}</div><p class="detail">${esc(x.detail)}</p><div class="meta">${x.transport?'🚇 '+esc(x.transport)+'<br>':''}${x.weather?'🌤️ '+esc(x.weather)+'<br>':''}${x.notes?'💡 '+esc(x.notes):''}</div><div class="actions">${x.link?`<a class="btn" href="${esc(x.link)}" target="_blank">Navegar</a>`:''}${x.source?`<a class="btn alt" href="${esc(x.source)}" target="_blank">Información</a>`:''}</div></div></div></article>`}
function bindChecks(){document.querySelectorAll('.checkrow input').forEach(c=>c.onchange=()=>{localStorage.setItem(c.dataset.key,c.checked?'1':'0');c.closest('.card').classList.toggle('done',c.checked)})}
function renderPlan(){let days=[...new Map(D.items.map(x=>[x.date,x.day]))];$('#daytabs').innerHTML='<button data-d="all">Todos</button>'+days.map(([d,n])=>`<button data-d="${d}">${n.slice(0,3)} ${d.slice(0,5)}</button>`).join('');$$('#daytabs button').forEach(b=>{b.classList.toggle('active',b.dataset.d===state.day);b.onclick=()=>{state.day=b.dataset.d;renderPlan()}});let q=$('#search').value.toLowerCase();let xs=D.items.filter(x=>(state.day==='all'||x.date===state.day)&&(!q||Object.values(x).join(' ').toLowerCase().includes(q)));$('#planlist').innerHTML=xs.map((x,i)=>card(x,i,'plan'+x.date)).join('')||'<div class="card">Sin resultados</div>';bindChecks()}
function nyNow(){return new Date(new Date().toLocaleString('en-US',{timeZone:'America/New_York'}))}function dmy(d){return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()}
function renderToday(){let n=nyNow(),key=dmy(n),xs=D.items.filter(x=>x.date===key);if(!xs.length){key='04/09/2026';xs=D.items.filter(x=>x.date===key);$('#todaytitle').textContent='Próximo viaje: viernes 4 de septiembre'}else $('#todaytitle').textContent='Plan de hoy';$('#nytime').textContent='Hora de Nueva York: '+new Intl.DateTimeFormat('es-ES',{timeZone:'America/New_York',dateStyle:'full',timeStyle:'short'}).format(new Date());$('#todayweather').innerHTML=xs[0]?.weather?`<strong>Clima orientativo del planning:</strong> ${esc(xs[0].weather)} <a href="https://www.weather.gov/okx/" target="_blank">ver previsión</a>`:'';$('#todaylist').innerHTML=xs.map((x,i)=>card(x,i,'today'+key)).join('');bindChecks()}
function initMap(){if(map||typeof L==='undefined')return;map=L.map('map').setView([40.758,-73.9855],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);D.places.forEach(p=>L.marker([p.lat,p.lng]).addTo(map).bindPopup(`<strong>${esc(p.name)}</strong><br>${esc(p.cat)}<br><a href="${p.nav}" target="_blank">Navegar</a>`));$('#placelist').innerHTML=D.places.map(p=>`<div class="place"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.cat)}</div></div><a class="btn" target="_blank" href="${p.nav}">Navegar</a></div>`).join('')}
function renderReservations(){let html=D.reservations.map((x,i)=>{let done=localStorage.getItem('res'+i)==='1';return `<article class="card ${done?'done':''}"><div class="checkrow"><input data-key="res${i}" type="checkbox" ${done?'checked':''}><div><span class="status ${esc(x.status)}">${esc(x.status)}</span><h3>${esc(x.title)}</h3><div class="muted">${esc(x.date)} · ${esc(x.time)}</div><p>${esc(x.detail)}</p>${x.doc?`<a class="btn" target="_blank" href="${x.doc}">Abrir documento</a>`:''}</div></div></article>`}).join('');$('#reservationlist').innerHTML=html;bindChecks();renderDocs()}
function renderDocs(){let cats=['Todos',...new Set(D.docs.map(x=>x.category))];$('#docfilters').innerHTML=cats.map(c=>`<button data-c="${esc(c)}" class="${c===state.doccat?'active':''}">${esc(c)}</button>`).join('');$$('#docfilters button').forEach(b=>b.onclick=()=>{state.doccat=b.dataset.c;renderDocs()});let xs=D.docs.filter(x=>state.doccat==='Todos'||x.category===state.doccat);$('#docgrid').innerHTML=xs.map(x=>`<a class="doc" target="_blank" href="${encodeURI(x.file)}"><span class="status">${esc(x.category)}</span><strong>${esc(x.title)}</strong><span class="muted">.${esc(x.type)}</span></a>`).join('')}
function renderInsurance(){let i=D.insurance;$('#insurance').innerHTML=`<div class="card insurance"><span class="status">${esc(i.product)}</span><h3>Póliza ${esc(i.policy)}</h3><p>Viaje ${esc(i.trip)} · ${esc(i.period)}</p><div class="emergency">📞 ${esc(i.phone)}</div><div class="actions"><a class="btn danger" href="tel:${i.phone.replace(/ /g,'')}">Llamar asistencia</a><a class="btn" href="https://wa.me/${i.whatsapp.replace(/\D/g,'')}" target="_blank">WhatsApp</a><a class="btn alt" href="mailto:${i.medical}">Email médico</a></div></div><div class="card"><h3>Coberturas destacadas</h3><ul>${i.summary.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="muted">Consultar límites y exclusiones en la póliza completa.</p></div><div class="docgrid">${D.docs.filter(x=>x.category==='Seguro IATI').map(x=>`<a class="doc" href="${encodeURI(x.file)}" target="_blank"><strong>${esc(x.title)}</strong></a>`).join('')}</div>`}
function expenses(){return JSON.parse(localStorage.getItem('expenses')||'[]')}function renderExpenses(){let xs=expenses(),tot=xs.reduce((s,x)=>s+(x.currency==='EUR'?x.amount:x.amount*x.rate),0);$('#total').textContent=tot.toLocaleString('es-ES',{style:'currency',currency:'EUR'});$('#expenselist').innerHTML=xs.length?xs.map((x,i)=>`<div class="expense-row"><div><strong>${esc(x.desc||x.cat)}</strong><div class="muted">${esc(x.date)} · ${esc(x.cat)}</div></div><div>${x.amount.toFixed(2)} ${x.currency}</div><button data-del="${i}">✕</button></div>`).join(''):'No hay gastos registrados.';$$('[data-del]').forEach(b=>b.onclick=()=>{let a=expenses();a.splice(+b.dataset.del,1);localStorage.setItem('expenses',JSON.stringify(a));renderExpenses()})}
$('#addexpense').onclick=()=>{let a=expenses(),amount=parseFloat($('#eamount').value);if(!amount)return;a.push({date:$('#edate').value,amount,currency:$('#ecurrency').value,cat:$('#ecat').value,desc:$('#edesc').value,rate:parseFloat($('#erate').value)||1});localStorage.setItem('expenses',JSON.stringify(a));$('#eamount').value='';$('#edesc').value='';renderExpenses()};$('#clearexpenses').onclick=()=>{if(confirm('¿Borrar todos los gastos?')){localStorage.removeItem('expenses');renderExpenses()}};$('#exportexpenses').onclick=()=>{let rows=[['Fecha','Descripción','Categoría','Importe','Moneda','Cambio USD-EUR'],...expenses().map(x=>[x.date,x.desc,x.cat,x.amount,x.currency,x.rate])];let blob=new Blob([rows.map(r=>r.join(';')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gastos_nueva_york.csv';a.click()};
// IndexedDB local documents
let dbp=new Promise((ok,no)=>{let r=indexedDB.open('nycdocs',1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id',autoIncrement:true});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});$('#fileinput').onchange=async e=>{let db=await dbp,tx=db.transaction('files','readwrite');for(let f of e.target.files)tx.objectStore('files').add({name:f.name,type:f.type,blob:f});tx.oncomplete=renderLocalDocs};async function renderLocalDocs(){let db=await dbp,tx=db.transaction('files'),r=tx.objectStore('files').getAll();r.onsuccess=()=>{$('#localdocs').innerHTML=r.result.map(x=>`<button class="doc" data-open="${x.id}"><strong>${esc(x.name)}</strong><span class="muted">Solo en este dispositivo</span></button>`).join('');$$('[data-open]').forEach(b=>b.onclick=async()=>{let db=await dbp,r=db.transaction('files').objectStore('files').get(+b.dataset.open);r.onsuccess=()=>window.open(URL.createObjectURL(r.result.blob),'_blank')})}};
function net(){let on=navigator.onLine;$('#network').textContent=on?'● Con conexión · mapas y enlaces disponibles':'● Sin conexión · planning, documentos y gastos siguen disponibles';$('#network').style.color=on?'#b8f5ce':'#ffd29d'}addEventListener('online',net);addEventListener('offline',net);net();$('#search').oninput=()=>{showView('planning');renderPlan()};$('#edate').value='2026-09-04';renderPlan();renderToday();renderReservations();renderInsurance();renderExpenses();renderLocalDocs();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
